### ISSUE TITLE
API Dokumentation: Anpassung und Umsetzung von gewünschten Fehlern

### ISSUE THREAD

**Issue by henrybrink** [SE-TINF22B2/G5-DuoGradus#163]
In der API Dokumentation fehlen derzeit noch einige Inhalte, außerdem gibt es bei einigen Endpunkten Unklarheiten, bzw. Änderungswünsche.
Im Detail wären das:

- [x] API Endpunkte verwenden konsequent den Plural, in der bisherigen Implementation wird jedoch bisher der Singular verwendet, @benedictweis hat sich eine Änderung auf den Singular gewünscht.
- [x] Derzeit gibt es noch keine wirklichen Endpunkte um die Verbindung zu Drittanbietern zu implementieren (diese sind für #138 notwendig)
- [x] Die Leaderboards sind noch nicht eindeutig zu verstehen. Eigentlich war ein direktes Freundesystem

 

*Wichtige Änderung*: Derzeit können "Aktivitäten" über die API abgerufen werden, dies entspricht jedoch nicht dem gewünschten Modell für die Anwendung, stattdessen ist folgendes gewünscht:
- [x] Es gibt "Ziele" für einen Nutzer, darunter fallen: Schritte & der Streak. Die Ziele können über einen Endpunkt abgerufen werden, welcher immer die Ziele für den aktuellen Tag zurückgibt.
- [x] Statt Aktivitäten gibt es "Aufgaben", diese Aufgaben entsprechen den Challenges aus #4.
- [x] Die "Activities" werden entfernt. Diese werden zwar von den Fitness-Anbietern bereitgestellt und sind Teil des Austauschformat (#139), allerdings ist ein direkter Zugriff durch den Anwender erstmal nicht notwendig.
